namespace api.mstiADM.SDK.csharp.Enums
{
    public enum ENomeTabela
    {
        Todas,
        TABPDUFs,
        TABPDCidades,
        TABPDPaises,
        TABVRUnidades,
        TABPDCESTs,
        TABPDNCMs,
        TABPDOrigensItens,
        TABPDTiposItens,
        TABPDRegimesTributarios,
        TABPDFinalidadesEmissoes,
        TABPDIndicadoresPresencas,
        TABPDModalidadesFretes,
        TABPDCFOPs,
        TABPDICMSCSTs,
        TABPDICMSCSOSNs,
        TABPDIPICSTs,
        TABPDPISCSTs,
        TABPDCOFINSCSTs,
        TABPDICMSModalidadesBaseCalculo,
        TABPDICMSModalidadesBaseCalculoST,
        TABPDICMSMotivosDesoneracao,
        TABPDIPIEnquadramentosLegais,
        TABPDANPs,
        TABPDMeiosDePagamento,

        TABPDCLSs,
        TABPDCNAEs,
        TABPDISSQNFormasTributacao,
        TABPDISSQNPISCOFINSCSTs,
        TABPDTiposImunidade,
        TABPDSimplesNacionalOpcoes,
        TABPDSimplesNacionalRegimesApuracao,
        TABPDRegimesTributariosEspeciais,
        TABPDNBSs,
        TABPDIBSCBSCSTs,
        TABPDIBSCBSCCLASSTRIBs,
        Nenhum
    }
}
