<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Authors>Microsum Tecnologia da Informação</Authors>
		<Copyright>Todos os direitos reservados à Microsum Tecnologia da Informação LTDA</Copyright>
	</PropertyGroup>

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NJsonSchema" Version="11.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="MessagePack" Version="2.5.172" />
		<PackageReference Include="MessagePack.Annotations" Version="2.5.172" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Constantes\" />
	  <Folder Include="Domain\" />
	  <Folder Include="Extensions\" />
	  <Folder Include="Resources\" />
	  <Folder Include="Services\" />
	</ItemGroup>

</Project>